use std::io::stdout;


/// There are 2 methods for type conversion;
/// 1- from which is an associated method (class or static method in Java)
/// 2- into is a self method (instance or Object method in Java)
///
/// It is preferred to impl Type::from() as .into() method can be inferred and autogenerated
/// by compiler most of the times.

fn main() {
    let str1: String = String::from("string slice"); // String::from() is a very famous type conversion instance, from slice to String
    let str2: String = "another string slice".into(); // it also convert to slice to String

    println!("str1: {}, str2: {}", str1, str2);
}
