[package]
name = "rust_from_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "word_counter"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.16.5", features = ["extension-module"] }
