[package]
name = "xml-format"
version = "0.1.0"
edition = "2021"

[dependencies]
minidom = "0.15.1"
xmltree = "0.10.3"

[[bin]]
name = "minidom"
path = "src/minidom.rs"

[[bin]]
name = "xmltree"
path = "src/xmltree.rs"