[package]
name = "log-example"
version = "0.1.0"
edition = "2021"

[dependencies]
# This is a facade to logging, much like log4j in Java world
log = "0.4.17"
# This is real implementation of logging
env_logger = "0.10.0"
# Another implementation of logging based on Log4j
log4rs = "1.2.0"